project:
  type: website


editor: source

website:
  # title: UBC Stat302
  # repo-url: https://github.com/ubc-stat/stat-302/
  # issue-url: https://github.com/ubc-stat/stat-302/issues/new/
  # repo-actions: [source, issue, edit]
  # page-navigation: true
  description: "Homepage for Stat302 Introduction to Probability at UBC, Spring 2025."
  open-graph: true
  page-footer:
    center: Copyright 2025, Matías Salibián-Barrera, Trevor Campbell, and Daniel J. McDonald
  sidebar:
    pinned: true
    logo: "style/stat302.png"
    background: primary
    foreground: white
    align: center
    style: docked
    search: true
    collapse-level: 1
    contents:
      - text: Home
        url: index.qmd
      - text: Syllabus
        url: syllabus.qmd
      - text: Schedule
        url: schedule.qmd
      - text: Assignments
        url: assignments/index.qmd

format:
  html:
    theme: [cosmo, style/stat302.scss]
    toc: true
    grid:
      sidebar-width: 400px
